In [ ]:
 import zipfile

In [ ]:
with zipfile.ZipFile("/content/housing.csv.zip","r") as zip_ref:
  zip_ref.extractall("/content")

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/housing.csv")

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [ ]:
df["ocean_proximity"].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [ ]:
df=pd.get_dummies(data=df,columns=["ocean_proximity"])

In [ ]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity_<1H OCEAN,ocean_proximity_INLAND,ocean_proximity_ISLAND,ocean_proximity_NEAR BAY,ocean_proximity_NEAR OCEAN
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,False,False,False,True,False
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,False,False,False,True,False
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,False,False,False,True,False
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,False,False,False,True,False
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,False,True,False,False,False
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,False,True,False,False,False
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,False,True,False,False,False
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,False,True,False,False,False
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,False,True,False,False,False

In [ ]:
df.isna().sum()

longitude                       0
latitude                        0
housing_median_age              0
total_rooms                     0
total_bedrooms                207
population                      0
households                      0
median_income                   0
median_house_value              0
ocean_proximity_<1H OCEAN       0
ocean_proximity_INLAND          0
ocean_proximity_ISLAND          0
ocean_proximity_NEAR BAY        0
ocean_proximity_NEAR OCEAN      0
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isna().sum()

longitude                     0
latitude                      0
housing_median_age            0
total_rooms                   0
total_bedrooms                0
population                    0
households                    0
median_income                 0
median_house_value            0
ocean_proximity_<1H OCEAN     0
ocean_proximity_INLAND        0
ocean_proximity_ISLAND        0
ocean_proximity_NEAR BAY      0
ocean_proximity_NEAR OCEAN    0
dtype: int64

In [ ]:
x=df.drop(columns=["median_house_value"])
y=df["median_house_value"]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
Scaler=StandardScaler()
x_train=Scaler.fit_transform(x_train)
x_test=Scaler.transform(x_test)

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
model=Sequential()
#input layer
model.add(Dense(x_train.shape[1],activation='relu',input_dim=x_train.shape[1]))
#Hidden Layer
model.add(Dense(512,kernel_initializer='normal', activation='relu'))
model.add(Dense(512,kernel_initializer='normal', activation='relu'))
model.add(Dense(256,kernel_initializer='normal', activation='relu'))
model.add(Dense(128,kernel_initializer='normal', activation='relu'))
model.add(Dense(64,kernel_initializer='normal', activation='relu'))
model.add(Dense(32,kernel_initializer='normal', activation='relu'))
#Output Layer
model.add(Dense(1,kernel_initializer='normal', activation = 'relu'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(loss="mse",optimizer=Adam(),metrics=["mse"])

In [ ]:
model.fit(x_train,y_train,epochs=15,batch_size=10,verbose=1)

Epoch 1/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 15s 8ms/step - loss: 8651480064.0000 - mse: 8651480064.0000
Epoch 2/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 4790949888.0000 - mse: 4790949888.0000
Epoch 3/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 4273370112.0000 - mse: 4273370112.0000
Epoch 4/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 4003324928.0000 - mse: 4003324928.0000
Epoch 5/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3828275200.0000 - mse: 3828275200.0000
Epoch 6/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3694383872.0000 - mse: 3694383872.0000
Epoch 7/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3636269056.0000 - mse: 3636269056.0000
Epoch 8/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3537232384.0000 - mse: 3537232384.0000
Epoch 9/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3492901120.0000 - mse: 3492901120.0000
Epoch 10/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3430280448.0000 - mse: 3430280448.0000
Epoch 11/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3450883584.0000 - mse: 3450883584.0000
Epoch 12/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 21s 8ms/step - loss: 3409379328.0000 - mse: 3409379328.0000
Epoch 13/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3375544576.0000 - mse: 3375544576.0000
Epoch 14/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3318559744.0000 - mse: 3318560000.0000
Epoch 15/15
1635/1635 ━━━━━━━━━━━━━━━━━━━━ 13s 8ms/step - loss: 3280801024.0000 - mse: 3280801024.0000

In [ ]:
model.evaluate(x_test,y_test)

128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3430368256.0000 - mse: 3430368256.0000

[3430368256.0, 3430368256.0]